version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./back-todo
    restart: always
    ports:
      - "3001:3000"
    env_file:
      - ./back-todo/.env
    depends_on:
      - mysql

  frontend:
    build:
      context: ./front-to-do/to-do-list
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql-data:
