version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234  
      MYSQL_DATABASE: bd_tarea
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql


  backend:
    build:
      context: ./back-todo
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./back-todo/.env
    environment:
      PRISMA_CLIENT_ENGINE_TYPE: mysql
      DATABASE_URL: mysql://root:1234@mysql:3306/bd_tarea
    depends_on:
      - mysql

  frontend:
    build:
      context: ./front-to-do/to-do-list
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql-data: